### Liste tous les livres
GET http://localhost:8082/livres
Accept: application/json

###

### Détail d'un livre
GET http://localhost:8082/livres/1
Accept: application/json

###

### Créer un livre
POST http://localhost:8082/livres
Content-Type: application/json

{
  "titre": "Les Bouts de bois de Dieu",
  "auteur": "Ousmane Sembène",
  "isbn": "978-2-07-036900-3",
  "genre": "Roman",
  "classeScolaire": "Terminale",
  "quantiteTotale": 3,
  "quantiteDisponible": 3
}

###

### Modifier un livre
PUT http://localhost:8082/livres/1
Content-Type: application/json

{
  "titre": "Le Monde s'effondre",
  "auteur": "Chinua Achebe",
  "isbn": "978-2-07-036822-8",
  "genre": "Roman",
  "classeScolaire": "Terminale",
  "quantiteTotale": 3,
  "quantiteDisponible": 2
}

###

### Supprimer un livre
DELETE http://localhost:8082/livres/4

###

### Emprunter un livre (décrémente quantiteDisponible)
PUT http://localhost:8082/livres/1/emprunter

###

### Retourner un livre (incrémente quantiteDisponible)
PUT http://localhost:8082/livres/1/retourner
