<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>sn.seydina</groupId>
  <artifactId>biblio-ms-demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>biblio-ms-demo</name>
  <description>Système de gestion de bibliothèque scolaire — projet parent</description>

  <modules>
    <module>discovery-svc</module>
    <module>gateway-svc</module>
    <module>membres-svc</module>
    <module>livres-svc</module>
    <module>emprunts-svc</module>
    <module>chatbot-svc</module>
  </modules>

</project>
