### Liste tous les membres
GET http://localhost:8081/membres
Accept: application/json

###

### Détail d'un membre
GET http://localhost:8081/membres/1
Accept: application/json

###

### Créer un membre
POST http://localhost:8081/membres
Content-Type: application/json

{
  "nom": "Sarr",
  "prenom": "Cheikh",
  "email": "cheikh.sarr@ecole.sn",
  "role": "ELEVE",
  "quota": 3
}

###

### Modifier un membre
PUT http://localhost:8081/membres/1
Content-Type: application/json

{
  "nom": "Diallo",
  "prenom": "Mamadou",
  "email": "mamadou.diallo@ecole.sn",
  "role": "ELEVE",
  "quota": 5
}

###

### Supprimer un membre
DELETE http://localhost:8081/membres/6

###

### Emprunts d'un membre (Feign → emprunts-svc)
GET http://localhost:8081/membres/1/emprunts
