spring:
  application:
    name: membres-svc
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:h2:mem:membres-db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  ai:
    mcp:
      server:
        name: membres-mcp-server
        version: 1.0.0

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
